apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: react-pvc
  namespace: react

spec:
  accessModes:
    - ReadWriteOnce

  storageClassName: manual

  resources:
    requests:
      storage: 1Gi
